-- Run once in the Supabase SQL editor. The backend must use a server-side
-- secret/service-role key; these tables are not directly accessible to users.
create table if not exists public.memories (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    user_message text not null,
    aura_reply text not null
);

create table if not exists public.screen_logs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    question text not null,
    reply_summary text not null
);

alter table public.memories enable row level security;
alter table public.screen_logs enable row level security;

-- No anon/authenticated policies: only the trusted backend should access data.
